export { default as displayUser } from './displayUser'
export { default as getPatients } from './getPatients'
export { default as getMedicalStaff } from './getMedicalStaff'
export { default as insertUser } from './insertUser'
export { default as removeUser } from './removeUser'
export { default as updateUser } from './updateUser'
export { default as updateDeviceToken } from './updateDeviceToken'
export { default as removeDeviceToken } from './removeDeviceToken'
export { default as updateAuthorizedUsers } from './updateAuthorizedUsers'
export { default as removeAuthorizedUsers } from './removeAuthorizedUsers'
export { default as hasUserwithPhoneNumber } from './hasUserwithPhoneNumber'

export * from './workingTimes'